"""remove big int from twitter

Revision ID: 115c33325bdf
Revises: 1b4e44e99d9d
Create Date: 2013-08-31 23:48:26.929109

"""

# revision identifiers, used by Alembic.
revision = '115c33325bdf'
down_revision = '1b4e44e99d9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
