"""

Revision ID: 186f386fb848
Revises: 2a39038becec
Create Date: 2013-09-14 18:54:57.530483

"""

# revision identifiers, used by Alembic.
revision = '186f386fb848'
down_revision = '2a39038becec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('last_changed', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'last_changed')
    ### end Alembic commands ###
