"""

Revision ID: 1b1fc53ecc42
Revises: 2e1a39f21db2
Create Date: 2013-09-14 10:04:50.033863

"""

# revision identifiers, used by Alembic.
revision = '1b1fc53ecc42'
down_revision = '2e1a39f21db2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
