"""

Revision ID: 2324e837f6ff
Revises: 186f386fb848
Create Date: 2013-09-14 18:56:33.813589

"""

# revision identifiers, used by Alembic.
revision = '2324e837f6ff'
down_revision = '186f386fb848'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
