"""

Revision ID: 2a39038becec
Revises: 36b62c09a9d3
Create Date: 2013-09-14 11:23:08.351336

"""

# revision identifiers, used by Alembic.
revision = '2a39038becec'
down_revision = '36b62c09a9d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
