"""

Revision ID: 2e1a39f21db2
Revises: 3381b3dbe79e
Create Date: 2013-09-14 10:00:39.042345

"""

# revision identifiers, used by Alembic.
revision = '2e1a39f21db2'
down_revision = '3381b3dbe79e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
