"""

Revision ID: 3381b3dbe79e
Revises: 359a97bf296c
Create Date: 2013-09-14 09:50:52.815710

"""

# revision identifiers, used by Alembic.
revision = '3381b3dbe79e'
down_revision = '359a97bf296c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
