"""item_textcol_limit

Revision ID: 346b3484b0c9
Revises: None
Create Date: 2013-09-01 19:42:02.730648

"""

# revision identifiers, used by Alembic.
revision = '346b3484b0c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
