"""fixchild

Revision ID: 359a97bf296c
Revises: 346b3484b0c9
Create Date: 2013-09-12 17:04:00.549950

"""

# revision identifiers, used by Alembic.
revision = '359a97bf296c'
down_revision = '346b3484b0c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
