"""

Revision ID: 36b62c09a9d3
Revises: 1b1fc53ecc42
Create Date: 2013-09-14 10:07:13.148336

"""

# revision identifiers, used by Alembic.
revision = '36b62c09a9d3'
down_revision = '1b1fc53ecc42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
