"""add big int from twitter

Revision ID: 441a00cddd37
Revises: 115c33325bdf
Create Date: 2013-08-31 23:49:27.032248

"""

# revision identifiers, used by Alembic.
revision = '441a00cddd37'
down_revision = '115c33325bdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
