"""rename twitter cols

Revision ID: 55de89cf5a1
Revises: 441a00cddd37
Create Date: 2013-09-01 00:02:39.482827

"""

# revision identifiers, used by Alembic.
revision = '55de89cf5a1'
down_revision = '441a00cddd37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter', sa.Column('fav_id', sa.BigInteger(), nullable=True))
    op.add_column('twitter', sa.Column('mention_id', sa.BigInteger(), nullable=True))
    op.drop_column('twitter', u'max_mention_id')
    op.drop_column('twitter', u'max_fav_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter', sa.Column(u'max_fav_id', sa.INTEGER(), nullable=True))
    op.add_column('twitter', sa.Column(u'max_mention_id', sa.INTEGER(), nullable=True))
    op.drop_column('twitter', 'mention_id')
    op.drop_column('twitter', 'fav_id')
    ### end Alembic commands ###
